version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_for_server
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/docker/mysql-for-server/data:/var/lib/mysql
  server:
    image: jeffyoun/cafe-server:latest
    container_name: server
    ports:
      - "80:80"
    command: "./wait-for-it.sh mysql:3306 --strict --timeout=300 -- java -Dserver.port=80 -jar /app.jar"
    depends_on:
      - mysql
    environment:
      PORT: 80
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DB_NAME: test
      DATABASE_USER: root
      DATABASE_PASSWORD: test
      SPRING_PROFILES_ACTIVE: dev,mysql
