logging.level:
  org.hibernate.SQL: info
  # org.hibernate.type: trace

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  pre-loading-enabled: true

jwt:
  header: Authorization
  secret: TOBE_OVERRIDE
  token-validity-in-secnods: 86400

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    mapper:
      accept-case-insensitive-enums: true

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY:SHOULD_BE_REPLACED}
      secret-key: ${SECRET_KEY:SHOULD_BE_REPLACED}
    s3:
      review-image-bucket: ${REVIEW_IMAGE_BUCKET:SHOULD_BE_REPLACED}
    cloud-front:
      image-domain: ${IMAGE_CLOUD_FRONT_DOMAIN:SHOULD_BE_REPLACED}
    region:
      static: ap-northeast-2
    stack:
      auto: false
