spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cafe
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: info
  # org.hibernate.type: trace
