SET REFERENTIAL_INTEGRITY FALSE
truncate table apple_auth
truncate table cafe_food_stat
truncate table cafe_keyword_stat
truncate table cafe_like
truncate table cafe_menu
truncate table cafe_purpose_stat
truncate table footprint
truncate table cafe
truncate table kakao_auth
truncate table local_auth
truncate table member_follow
truncate table menu
truncate table profile_image
truncate table review_cafe_keyword
truncate table cafe_keyword
truncate table review_comment
truncate table review_food_info
truncate table review_image
truncate table review_like
truncate table member
truncate table review
SET REFERENTIAL_INTEGRITY TRUE
